services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "4242:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd123
    restart: unless-stopped

networks:
  dev-network:
    driver: bridge

volumes:
  sql_data:
  portainer_data: