services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: "on-failure:5"
    ports:
      - "4242:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    user: root
    container_name: sqlserver
    restart: "on-failure:5"
    deploy:
      resources:
        limits:
          memory: 2g # Limite de memória que será consumida pelo container
        reservations:
          memory: 1g # Recurso mínimo que a máquina precisa ter disponivel para rodar o container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data

volumes:
  portainer_data:
  mssql_data:
  rabbitmq_data: